
[project]
name = "core-contracts"

[repl]
costs_version = 1

[contracts.bns]
path = "../../src/chainstate/stacks/boot/bns.clar"
depends_on = []

[contracts.stacker-db]
path = "../../src/chainstate/stacks/boot/stacker-db.clar"
depends_on = []