[workspace]
resolver = "2"
members = [
    "stackslib",
    "stacks-common",
    "pox-locking",
    "clarity",
    "stx-genesis",
    "libstackerdb",
    "libsigner",
    "stacks-signer",
    "testnet/stacks-node"]

# Use a bit more than default optimization for
#  dev builds to speed up test execution
[profile.dev]
opt-level = 1

# Use release-level optimization for dependencies
# This slows down "first" builds on development environments,
#  but won't impact subsequent builds.
[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = true

[patch.crates-io]
p256k1 = { path = "/home/jude/pkg/p256k1/p256k1", version = "5.5.0" }
wsts = { path = "/home/jude/pkg/wsts" }
