[package]
name = "blockstack-core"
version = "0.0.1"
authors = ["Jude Nelson <judecn@gmail.com>"]
license = "GPLv3"
homepage = "https://github.com/jcnelson/blockstack-ng"
repository = "https://github.com/jcnelson/blockstack-ng"
description = "Reference implementation of Blockstack Core"
keywords = [ "bitcoin", "crypto", "blockstack", "decentralized", "dapps", "blockchain" ]
readme = "README.md"

[dependencies]
bitcoin = "0.14.2"
jsonrpc = "0.10.2"
rust-ini = "0.13"
log = "0.4"
rand = "0.5"
serde = "1"
serde_derive = "1"
secp256k1 = "0.11.5"
rust-crypto = "0.2" 
sha2 = "0.8.0"
dirs = "1.0.4"

[dependencies.rusqlite]
version = "0.15.0"
# features = ["bundled"]

[dependencies.ed25519-dalek]
version = "1.0.0-pre.0"
features = ["serde"]

[dependencies.curve25519-dalek]
version = "1.0.0-pre.0"
features = ["serde"]

