version: 2
jobs:
  build:
    working_directory: ~/blockstack
    docker:
      - image: ablankstein/circleci-rust-kcov
    steps:
      - checkout
      - run:
          command: |
            rustup override set nightly && cargo build
      - run:
          environment:
            RUST_BACKTRACE: 1
            BLOCKSTACK_DEBUG: 1
            RUSTFLAGS: -Clink-dead-code
          command: |
            rustup override set nightly && cargo kcov && bash <(curl -s https://codecov.io/bash)
