version: 2
jobs:
  build:
    working_directory: ~/blockstack
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          command: |
            cd blockstack-vm && cargo build
      - run:
          environment:
            RUST_BACKTRACE: 1
            BLOCKSTACK_DEBUG: 1
          command: |
            cd blockstack-vm && cargo test -- --nocapture --test-threads=1
