version: 2
jobs:
  build:
    working_directory: ~/blockstack
    docker:
      - image: ablankstein/circleci-rust-kcov
    steps:
      - checkout
      - run:
          command: |
            cd blockstack-vm && cargo build
      - run:
          environment:
            RUST_BACKTRACE: 1
            BLOCKSTACK_DEBUG: 1
            RUSTFLAGS: -Clink-dead-code
          command: |
            cd blockstack-vm && cargo kcov && /root/.codecov
