version: 2
jobs:
  deploy:
    working_directory: /build
    docker:
      - image: rust:1.34-stretch
    steps:
      - checkout
      - run:
          command: |
            bash build-scripts/start-builds.sh
      - store_artifacts:
          path: /build/dist/
          destination: dist/
  build:
    machine: true
    working_directory: ~/blockstack
    steps:
      - checkout
      - run:
          name: Pull Cargo Tarpaulin Image
          command: |
            docker pull xd009642/tarpaulin
      - run:
          name: Run tests in Cargo Tarpaulin Image
          command: |
            docker run --security-opt seccomp=unconfined -e RUST_BACKTRACE=1 -e BLOCKSTACK_DEBUG=1 \
            -e RUSTFLAGS=-Clink-dead-code -v "$PWD:/volume" xd009642/tarpaulin cargo tarpaulin -t 300 -o Xml \
            -- --test-threads 1
      - run:
          name: Upload to codecov.io
          command: |
            bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy
