[node]
name = "helium-node"
rpc_bind = "127.0.0.1:9000"

[burnchain]
chain = "bitcoin"
mode = "regtest"
block_time = 5000

[mempool]
path = "/tmp/mempool"

[[mstx_balance]]
address = "STGT7GSMZG7EA0TS6MVSKT5JC1DCDFGZWJJZXN8A"
amount = 10000

[[mstx_balance]]
address = "ST1JA3KG2CQY67FZ071BSHMT18CQPCQVMNZ6A7XE6"
amount = 100000

[[mstx_balance]]
address = "ST2VHM28V9E5QCRD6C73215KAPSBKQGPWTEE5CMQT"
amount = 10000
