[package]
name = "stacks-common"
version = "0.0.1"
authors = [ "Jude Nelson <jude@stacks.org>",
            "Aaron Blankstein <aaron@blockstack.com>",
            "Ludo Galabru <ludovic@blockstack.com>" ]
license = "GPLv3"
homepage = "https://github.com/blockstack/stacks-blockchain"
repository = "https://github.com/blockstack/stacks-blockchain"
description = "Common modules for blockstack_lib, libclarity"
keywords = [ "stacks", "stx", "bitcoin", "crypto", "blockstack", "decentralized", "dapps", "blockchain" ]
readme = "README.md"

[lib]
name = "stacks_common"
path = "./src/libcommon.rs"

[dependencies]
rand = "=0.7.2"
serde = "1"
serde_derive = "1"
serde_stacker = "0.1"
sha3 = "0.8.2"
ripemd160 = "0.8.0"
lazy_static = "1.4.0"
percent-encoding = "2.1.0"
sha2 = "0.8.0"
slog = { version = "2.5.2", features = [ "max_level_trace" ] }
slog-term = "2.6.0"
slog-json = { version = "2.3.0", optional = true }
chrono = "0.4.19"
libc = "0.2.82"

[dependencies.serde_json]
version = "1.0"
features = ["arbitrary_precision", "unbounded_depth"]

[dependencies.secp256k1]
version = "0.19.0"
features = ["serde", "recovery"]

[dependencies.rusqlite]
version = "=0.24.2"
features = ["blob", "serde_json", "i128_blob", "bundled", "trace"]

[dependencies.ed25519-dalek]
version = "=1.0.0-pre.3"
features = ["serde"]

[dependencies.curve25519-dalek]
version = "=2.0.0"
features = ["serde"]

[dependencies.time]
version = "0.2.23"
features = ["std"]

[dev-dependencies]
rstest = "0.11.0"
rstest_reuse = "0.1.3"
assert-json-diff = "1.0.0"

[features]
default = ["developer-mode"]
developer-mode = []
slog_json = ["slog-json"]
testing = []

[target.'cfg(all(target_arch = "x86_64", not(target_env = "msvc")))'.dependencies]
sha2-asm = "0.5.3"
