[package]
name = "stacks-core"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
sha2 = "^0.10.7"
ripemd = "^0.1.3"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0.43"
