[package]
name = "stacks-signer"
version = "0.0.1"
license = "GPLv3"
homepage = "https://github.com/blockstack/stacks-blockchain"
repository = "https://github.com/blockstack/stacks-blockchain"
edition = "2021"

[[bin]]
name = "stacks-signer"
path = "src/main.rs"

[lib]
path = "src/lib.rs"    # The source file of the target.
crate-type = ["lib"]   # The crate types to generate.

[dependencies]
sha3 = "0.10.6"
serde = { version = "1.0", features = ["serde_derive"] }
toml = "0.5.9"
hashbrown = { version = "0.13", features = ["serde"] }
frost = { git = "https://github.com/trust-machines/frost", branch = "multiple-parties-per-signer" }
rand_core = { version  = "0.5"}
itertools = "^0.10.5"
secp256k1-math = { git = "https://github.com/Trust-Machines/rust-secp256k1-math", rev = "ad35f79ce18d67fdd3c11697066b28ea38c5fbde"  }
ureq = { version = "2.6", features = [] }
stacks-common = { path = "../../stacks-common" }
slog = { version = "2.5.2", features = [ "max_level_trace" ] }
slog-term = "2.6.0"
slog-json = { version = "2.3.0", optional = true }

[build-dependencies]
build-utils = { path = "../../build-utils" }

