[package]
name = "stacks-signer"
version = "0.0.1"
license = "GPLv3"
homepage = "https://github.com/blockstack/stacks-blockchain"
repository = "https://github.com/blockstack/stacks-blockchain"
edition = "2021"

[[bin]]
name = "stacks-signer"
path = "src/main.rs"

[dependencies]
sha3 = "0.10.6"
serde = { version = "1.0", features = ["serde_derive"] }
slog = "2.7.0"
slog-async = "2.7.0"
slog-term = "2.9.0"
toml = "0.5.9"
frost = { git = "https://github.com/trust-machines/frost" }
rand_core = { version  = "0.5"}
