[package]
name = "stacks-signer"
version = "0.0.1"
license = "GPLv3"
homepage = "https://github.com/blockstack/stacks-blockchain"
repository = "https://github.com/blockstack/stacks-blockchain"
edition = "2021"

[[bin]]
name = "stacks-signer"
path = "src/main.rs"

[dependencies]
sha3 = "0.10.6"
serde = { version = "1.0", features = ["serde_derive"] }
toml = "0.5.9"
hashbrown = { version = "0.13", features = ["serde"] }
frost = { git = "https://github.com/trust-machines/frost", branch = "feat/serde_support" }
rand_core = { version  = "0.5"}
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
itertools = "^0.10.5"
secp256k1-math = { git = "https://github.com/Trust-Machines/rust-secp256k1-math", rev = "ad35f79ce18d67fdd3c11697066b28ea38c5fbde"  }
async-std = { version = "^1.10", features = ["attributes"] }
libp2p = { version = "^0.50", features = ["tcp", "dns", "async-std", "websocket", "noise", "mplex", "yamux", "floodsub"] }
ed25519-dalek = { version = "^1.0.1", features = [] }

[build-dependencies]
build-utils = { path = "../../build-utils" }

