[package]
name = "stx-genesis"
version = "0.1.0"
authors = ["Matthew Little <matthew@blockstack.com>"]
edition = "2018"

[dependencies]
libflate = "1.0.3"

[lib]
name = "stx_genesis"
path = "src/lib.rs"

[build-dependencies]
libflate = "1.0.3"

[target.'cfg(all(any(target_arch = "x86_64", target_arch = "x86", target_arch = "aarch64"), not(target_env = "msvc")))'.build-dependencies]
sha2 = { version = "0.10", features = ["asm"] }

[target.'cfg(any(not(any(target_arch = "x86_64", target_arch = "x86", target_arch = "aarch64")), target_env = "msvc"))'.build-dependencies]
sha2 = { version = "0.10" }