version: '2'
services:
  mongodb:
    image: mongo:3.4
    volumes:
      - './data/mongodb/:/data/db'
    networks:
      - api
    restart: always

  blockstack-api:
    image: 'quay.io/blockstack/blockstack-core:master'
    command: blockstack api start-foreground -y --debug --password dummywalletpassword
    volumes:
      - './data/blockstack-api:/root/.blockstack'
      - './data/blockstack-api/tmp:/tmp'
    networks:
      - api
    environment:
      - BLOCKSTACK_CLIENT_INTERACTIVE_YES=0
    restart: always

  search-indexer:
    build:
      context: ../
      dockerfile: api/search/Dockerfile
    environment:
      - BLOCKSTACK_DEBUG=0
      - PUBLIC_NODE=True
      - DEFAULT_HOST=0.0.0.0
      - MONGODB_URI=mongodb://mongodb
    networks:
      - api
    restart: always
    links:
      - mongodb
      - blockstack-api
    volumes:
      - "./data/search-api/:/var/blockstack-search"

  search-api:
    build:
      context: ../
      dockerfile: api/Dockerfile
    environment:
      - BLOCKSTACK_DEBUG=1
      - PUBLIC_NODE=True
      - DEFAULT_HOST=0.0.0.0
      - MONGODB_URI=mongodb://mongodb
      - BASE_API_URL=http://blockstack-api:6270
      - DEBUG=True
    networks:
      - api
    ports:
      - 3000:3000
    restart: always
    links:
      - mongodb
      - blockstack-api
    volumes:
      - "./data/search-api/:/var/blockstack-search"

networks:
  api: null
