# Cancels outdated stacks-blockchain workflow runs when triggered by fork PRs
name: Cancel
on:
  workflow_run:
    workflows: ["stacks-blockchain"]
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.8.0
      with:
        workflow_id: ${{ github.event.workflow.id }}
