name: cargo-tests

on:
  push:
    branches:
      - 'master'
      - 'gh-workflow-cargo'
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: rust:1.45-stretch
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          cargo test --workspace && cargo test -- --ignored --test-threads 1
          
  demo-tests:
    runs-on: ubuntu-latest
    container: rust:1.45-stretch
    steps:
      - uses: actions/checkout@v2
      - name: Run demo tests
        run: |
          cargo build
          ./target/debug/blockstack-core local initialize db &&
          ./target/debug/blockstack-core local check sample-contracts/tokens.clar db &&
          ./target/debug/blockstack-core local launch S1G2081040G2081040G2081040G208105NK8PE5.tokens sample-contracts/tokens.clar db &&
          ./target/debug/blockstack-core local check sample-contracts/names.clar db &&
          ./target/debug/blockstack-core local launch S1G2081040G2081040G2081040G208105NK8PE5.names sample-contracts/names.clar db &&
          ./target/debug/blockstack-core local execute db S1G2081040G2081040G2081040G208105NK8PE5.tokens mint! SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR u100000
          echo "(get-balance 'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR)" | ./target/debug/blockstack-core local eval S1G2081040G2081040G2081040G208105NK8PE5.tokens db
