name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:      
  dist:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [ windows_x64, macos_x64, linux_x64, linux_musl_x64, linux_musl_x64, linux_armv7, linux_arm64 ]

    steps:
      - uses: actions/checkout@v2

      - name: Build distributable
        env:
          DIST_TARGET_FILTER: ${{ matrix.platform }}
        run: build-scripts/build-dist.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/